### ISSUE TITLE
AMD/Linux descriptors issue

### ISSUE THREAD

**Issue by cmdrDiscoCat** [lknknm/ottocento-engine#27] opened 2024-10-23 19:58 UTC
When I try to launch the executable, no window opens, and here's what it shows in the terminal where I launched it :

[debug_ottoceto.txt](https://github.com/user-attachments/files/17497520/debug_ottoceto.txt)

It returned 1, too.

I'm joining the debug file, the launching.txt file (which is the "regular" output when launching the program) and the vulkaninfo output:

[launching.txt](https://github.com/user-attachments/files/17497561/launching.txt)
[vulkaninfo.txt](https://github.com/user-attachments/files/17497562/vulkaninfo.txt)
[vulkaninfo_summary.txt](https://github.com/user-attachments/files/17497563/vulkaninfo_summary.txt)

My configuration : 

OS: Arch Linux x86_64
Kernel: 6.11.5-zen1-1-zen
CPU: AMD Ryzen 7 3700X (16) @ 4.43 GHz
GPU: AMD Radeon RX 6700 XT [Discrete] (amdvlk driver)
Memory: 5385 MiB / 15898 MiB

**Comment by lknknm** [comment] 2024-10-23 22:19
Thanks for submitting!

**Comment by lknknm** [comment] 2024-11-03 03:34
So after the help from Evie and Eearslya on the Vulkan Discord, they guided through some steps to make it finally work.
I'll be documenting it here before I close the issue so we can keep track of it if we need down the line.

On the `OttDevice::createInstance()` I had to check the `VkApplicationInfo appInfo.apiVersion` which had the wrong version set as `VK_API_VERSION_1_0`. The struct was updated to use the `VK_API_VERSION_1_3`:
```cpp
VkApplicationInfo   appInfo {
                    .sType              = VK_STRUCTURE_TYPE_APPLICATION_INFO,
                    .pApplicationName   = "OttocentoEngine",
                    .applicationVersion = VK_MAKE_VERSION(1, 0, 0),
                    .pEngineName        = "No Engine",
                    .engineVersion      = VK_MAKE_VERSION(1, 0, 0),
                    .apiVersion         = VK_API_VERSION_1_3,
};
 ```
 This requires to update our previous extensions implementation inside `OttDevice::createLogicalDevice()` to accept the `descriptorBindingPartiallyBound` too:
 ```cpp
     VkPhysicalDeviceVulkan12Features physicalDeviceVulkan12Features {
                                .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_VULKAN_1_2_FEATURES,
                                .shaderSampledImageArrayNonUniformIndexing = VK_TRUE,
                                .descriptorBindingPartiallyBound           = VK_TRUE,
                                .descriptorBindingVariableDescriptorCount  = VK_TRUE,
                                .runtimeDescriptorArray                    = VK_TRUE
    };
    
    VkPhysicalDeviceFeatures2 deviceFeatures {
                                .sType = VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_FEATURES_2,
                                .pNext = &physicalDeviceVulkan12Features,
                                .features = {.sampleRateShading = VK_TRUE,
                                                .samplerAnisotropy = VK_TRUE, }
    };

    VkDeviceCreateInfo createInfo {
                                .sType = VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO,
                                .pNext = &deviceFeatures,
                                .queueCreateInfoCount    = static_cast<uint32_t>(queueCreateInfos.size()),
                                .pQueueCreateInfos       = queueCreateInfos.data(),
                                .enabledExtensionCount   = static_cast<uint32_t>(deviceExtensions.size()),
                                .ppEnabledExtensionNames = deviceExtensions.data(),
    };
```
 
 The second part of the problem is that we are having trouble in allocating the DescriptorSets. According to Eearslya: "Nvidia basically doesn't care about descriptor pools at all, that's why it works [just fine on Nvidia GPUs]. [...] People who start on AMD have it easy because the driver is strict, people who start on NVidia have a driver that says 'eh whatever'". 
This means that for AMD we need to explicitly specify the correct amount of descriptor pools we want for our sampler.
 
So, for my samplerLayoutBinding inside `OttApplication::createObjectDescriptorSetLayout()`:
```cpp
VkDescriptorSetLayoutBinding samplerLayoutBinding {
    .binding            = 1,
    .descriptorType     = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
    .descriptorCount    = TEXTURE_ARRAY_SIZE * MAX_FRAMES_IN_FLIGHT,
    .stageFlags         = VK_SHADER_STAGE_FRAGMENT_BIT,
};
```

and for my descriptorPool sizes:
```cpp
std::array<VkDescriptorPoolSize, 2> poolSizes{};
poolSizes[0].type = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER; 
poolSizes[0].descriptorCount = static_cast<uint32_t>(MAX_FRAMES_IN_FLIGHT);
poolSizes[1].type = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER;
poolSizes[1].descriptorCount = static_cast<uint32_t>(TEXTURE_ARRAY_SIZE * MAX_FRAMES_IN_FLIGHT * 2);
 ```
 
 This way the issue was finally fixed in the commit https://github.com/lknknm/ottocento-engine/commit/179b8c7dce297babb0cacb68561ea3f0608365eb. Unfortunately this is a hard problem to debug, because what can work for Nvidia GPUs won't necessarily work for AMD GPUs. Vulkan still doesn't have validation for descriptors, so we could maybe think about other ways to test, debug and validate implementations on different GPU vendors.

**Closed by lknknm** 2024-11-03 03:34 UTC
Labels: bug
